ALTER TABLE "StoreSetting" ADD COLUMN "paymentFeePct" DOUBLE PRECISION NOT NULL DEFAULT 2;
ALTER TABLE "StoreSetting" ADD COLUMN "codFeePct" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "StoreSetting" ADD COLUMN "codFeeFlat" INTEGER NOT NULL DEFAULT 0;
